echo "set number" >> ~/.vimrc
echo "set showcmd" >> ~/.vimrc
echo "set cursorline" >> ~/.vimrc
echo "set mouse=a" >> ~/.vimrc
echo "syntax enable" >> ~/.vimrc
echo "colorscheme slate " >> ~/.vimrc
echo >> ~/.vimrc
echo "set t_Co=256" >> ~/.vimrc
echo "set background=dark" >> ~/.vimrc
echo "highlight Normal ctermbg=NONE" >> ~/.vimrc
echo "highlight nonText ctermbg=NONE" >> ~/.vimrc
echo >> ~/.vimrc
echo "set smarttab" >> ~/.vimrc
echo "set shiftwidth=4" >> ~/.vimrc
echo "set tabstop=4" >> ~/.vimrc
echo "set softtabstop=4" >> ~/.vimrc
echo "set expandtab" >> ~/.vimrc
echo >> ~/.vimrc
echo "set lbr" >> ~/.vimrc
echo >> ~/.vimrc
echo "set ai" >> ~/.vimrc
echo "set si" >> ~/.vimrc
echo "set wrap" >> ~/.vimrc
echo >> ~/.vimrc
echo "set lazyredraw" >> ~/.vimrc
echo >> ~/.vimrc
echo "set incsearch" >> ~/.vimrc
echo "set hlsearch" >> ~/.vimrc
echo "nnoremap <leader><space> :nohlsearch<CR>" >> ~/.vimrc
echo "set showmatch" >> ~/.vimrc
echo >> ~/.vimrc
echo "nnoremap j gj" >> ~/.vimrc
echo "nnoremap k gk" >> ~/.vimrc
echo >> ~/.vimrc
echo "nnoremap B ^" >> ~/.vimrc
echo "nnoremap E $" >> ~/.vimrc
echo >> ~/.vimrc
echo "nnoremap $ <nop>" >> ~/.vimrc
echo "nnoremap ^ <nop>" >> ~/.vimrc
echo >> ~/.vimrc
echo "nnoremap jk <esc>" >> ~/.vimrc